# Generated by Django 4.1.3 on 2022-11-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='family',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.family'),
        ),
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(blank=True, choices=[('0', 'Father'), ('1', 'Mother'), ('2', 'Son'), ('3', 'Daughter'), ('4', 'Sister'), ('5', 'Brother')], max_length=1),
        ),
    ]
