# Generated by Django 4.1.4 on 2023-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('0', 'Father'), ('1', 'Mother'), ('2', 'Son'), ('3', 'Daughter'), ('4', 'Sister'), ('5', 'Brother'), ('6', 'Husband'), ('7', 'Wife'), ('8', 'None')], max_length=1, null=True),
        ),
    ]
