# Generated by Django 4.1.3 on 2023-02-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_costs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='costs',
        ),
    ]
